# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f30b1cea4f157c23b74b37ed86cb7aee"
name = "shop-chat-agent-v3"
handle = "shop-chat-agent-v3"
application_url = "https://screening-declare-friend-encyclopedia.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://screening-declare-friend-encyclopedia.trycloudflare.com/auth/callback",
  "https://screening-declare-friend-encyclopedia.trycloudflare.com/auth/shopify/callback",
  "https://screening-declare-friend-encyclopedia.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[app_proxy]
url = "https://screening-declare-friend-encyclopedia.trycloudflare.com"
subpath = "chat"
prefix = "apps"
