# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a840674b47a51a88151b77b53ed7bece"
name = "shop-chat-agent-v2"
handle = "shop-chat-agent-v2"
application_url = "https://pm-kerry-coast-backgrounds.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://pm-kerry-coast-backgrounds.trycloudflare.com/auth/callback",
  "https://pm-kerry-coast-backgrounds.trycloudflare.com/auth/shopify/callback",
  "https://pm-kerry-coast-backgrounds.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "https://pm-kerry-coast-backgrounds.trycloudflare.com"
subpath = "chat"
prefix = "apps"
